# QCoder Configuration Example
# Copy this file to config.yaml and customize

# AI Model Configuration
model: qwen/qwen3-coder:free
max_context_length: 8000

# API Keys (prefer environment variables)
# api_key: your_openrouter_api_key_here
# github_token: your_github_token_here

# Logging
log_level: INFO  # DEBUG, INFO, WARNING, ERROR

# Conversation Settings
conversation_history_dir: .qcoder/conversations

# Plugin Settings
enable_plugins: true

# Custom Settings (project-specific)
# project_name: My Project
# coding_standards: strict
